image: Ubuntu2004

stack: jdk 11

branches:
  only:
    - main

build: off

install:
  - docker-compose up --build --detach
  - sleep 30
  - java -jar ./artifacts/aqa-shop.jar &
  - chmod +x gradlew

build_script:
  - ./gradlew test --info -Dselenide.headless=true